### PR TITLE
Configure swagger and add metadata goodies

### PR DESCRIPTION
**Pull request by he-james**
Completes #5 

Checkout swagger by running and going to localhost:3000/api

### CODE REVIEW

**Review by sdmungov — APPROVED** [review]

**Comment by sdmungov** [comment]
@he-james lgtm feel free to merge

**Review by FB-Reda — APPROVED** [review]
I am not a swagger expert or anything, but looks good to me!

@sdmungov Are we tracking our package-lock file in repo or should it be added to git ignore? I know some teams go both ways on this.

**Comment by sdmungov** [comment]
> I am not a swagger expert or anything, but looks good to me!
> 
> @sdmungov Are we tracking our package-lock file in repo or should it be added to git ignore? I know some teams go both ways on this.

@FB-Reda I don't have a preference or strong opinion one way or another, have been on projects that have added all lock files to gitignore and been on projects that haven't and i really didn't really experience any differences from my frontend dev day to day perspective. So I say we just choose and go with it or I can look more into it and see if there is a better long move.

**Comment by he-james** [comment]
> @sdmungov Are we tracking our package-lock file in repo or should it be added to git ignore? I know some teams go both ways on this.

I'm removing this shit from my repo, my bad

**Comment by he-james** [comment]
i hate bloat

**Pull request merged**
